"""add number, date column on policy_documents table

Revision ID: 7c22ee226375
Revises: 
Create Date: 2025-05-25 17:27:47.921675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c22ee226375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_documents', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
